set -g status-left-length 20
set -g status-style bg=default,fg=#cdd6f4
set -g status-left '#[fg=#cba6f7][#S] '
set -g status-right '#[fg=#fab387]%Y-%m-%d #[fg=#cdd6f4]%H:%M'
setw -g window-status-current-style fg=#f38ba8,bg=default,bold
setw -g window-status-style fg=#585b70,bg=default
