set -g status-left-length 20
set -g status-style bg=default,fg=#f8f8f2
set -g status-left '#[fg=#bd93f9][#S] '
set -g status-right '#[fg=#ffb86c]%Y-%m-%d #[fg=#f8f8f2]%H:%M'
setw -g window-status-current-style fg=#ff79c6,bg=default,bold
setw -g window-status-style fg=#6272a4,bg=default
