set -g status-left-length 20
set -g status-style bg=default,fg=#d4be98
set -g status-left '#[fg=#d3869b][#S] '
set -g status-right '#[fg=#d8a657]%Y-%m-%d #[fg=#d4be98]%H:%M'
setw -g window-status-current-style fg=#ea6962,bg=default,bold
setw -g window-status-style fg=#928374,bg=default
