set -g status-left-length 20
set -g status-style bg=default,fg=#dcd7ba
set -g status-left '#[fg=#957fb8][#S] '
set -g status-right '#[fg=#e6c384]%Y-%m-%d #[fg=#dcd7ba]%H:%M'
setw -g window-status-current-style fg=#7fb4ca,bg=default,bold
setw -g window-status-style fg=#727169,bg=default
