set -g status-left-length 20
set -g status-style bg=default,fg=#d6deeb
set -g status-left '#[fg=#c792ea][#S] '
set -g status-right '#[fg=#ecc48d]%Y-%m-%d #[fg=#d6deeb]%H:%M'
setw -g window-status-current-style fg=#82aaff,bg=default,bold
setw -g window-status-style fg=#5f7e97,bg=default
