set -g status-left-length 20
set -g status-style bg=default,fg=#e0def4
set -g status-left '#[fg=#c4a7e7][#S] '
set -g status-right '#[fg=#f6c177]%Y-%m-%d #[fg=#e0def4]%H:%M'
setw -g window-status-current-style fg=#eb6f92,bg=default,bold
setw -g window-status-style fg=#908caa,bg=default
