set -g status-left-length 20
set -g status-style bg=default,fg=#c0caf5
set -g status-left '#[fg=#bb9af7][#S] '
set -g status-right '#[fg=#ff9e64]%Y-%m-%d #[fg=#c0caf5]%H:%M'
setw -g window-status-current-style fg=#f7768e,bg=default,bold
setw -g window-status-style fg=#565f89,bg=default
