[env]
TERM = "xterm-256color"

[scrolling]
history = 10000

[font]
size = 19

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"

[font.offset]
x = 1
y = 0

[window]
decorations = "Buttonless"
dynamic_padding = false
startup_mode = "Windowed"

dimensions.columns = 208
dimensions.lines = 46

padding.x = 7
padding.y = 3


 # opacity = 0.8
 # blur = true

option_as_alt = "Both"

[cursor]
blink_interval = 500  # Optional, default is 750ms
unfocused_hollow = true

[cursor.style]
shape = "Block"        # Options: "Block", "Underline", "Beam"
blinking = "Always"    # Options: "Never", "Off", "On", "Always"


[general]
live_config_reload = true
 import  = [ "~/.config/alacritty/themes/gruvbox-material-medium.toml" ]
